// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getGroup = `-- name: GetGroup :one
SELECT id, name, created_at FROM groups WHERE id = $1
`

func (q *Queries) GetGroup(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i Group
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const renameGroup = `-- name: RenameGroup :one
UPDATE groups SET name = $2 WHERE id = $1
RETURNING id, name, created_at
`

type RenameGroupParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) RenameGroup(ctx context.Context, arg RenameGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, renameGroup, arg.ID, arg.Name)
	var i Group
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}
