// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const averageServedCount = `-- name: AverageServedCount :one
SELECT COALESCE(AVG(m.baseline_picks + COALESCE(p.cnt, 0)), 0)::float8 AS avg_served
FROM memberships m
LEFT JOIN (
  SELECT picker_id, COUNT(*) FILTER (WHERE is_credited) AS cnt
  FROM picks pk
  WHERE pk.group_id = $1
  GROUP BY picker_id
) p ON p.picker_id = m.user_id
WHERE m.group_id = $1 AND m.status = 'active' AND m.role = 'core'
`

func (q *Queries) AverageServedCount(ctx context.Context, groupID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, averageServedCount, groupID)
	var avg_served float64
	err := row.Scan(&avg_served)
	return avg_served, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name) VALUES ($1)
RETURNING id, name, letterboxd_user, created_at
`

func (q *Queries) CreateUser(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LetterboxdUser,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateMembership = `-- name: DeactivateMembership :one
UPDATE memberships
SET status = 'inactive', left_at = now()
WHERE group_id = $1 AND user_id = $2
RETURNING id, group_id, user_id, role, status, baseline_picks, rotation_position, joined_at, left_at
`

type DeactivateMembershipParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) DeactivateMembership(ctx context.Context, arg DeactivateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, deactivateMembership, arg.GroupID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.BaselinePicks,
		&i.RotationPosition,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const getGroupMember = `-- name: GetGroupMember :one
SELECT u.id AS user_id, u.name, m.role, m.status, m.baseline_picks, m.joined_at
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.group_id = $1 AND m.user_id = $2
`

type GetGroupMemberParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

type GetGroupMemberRow struct {
	UserID        uuid.UUID          `json:"user_id"`
	Name          string             `json:"name"`
	Role          MembershipRole     `json:"role"`
	Status        MembershipStatus   `json:"status"`
	BaselinePicks int32              `json:"baseline_picks"`
	JoinedAt      pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (GetGroupMemberRow, error) {
	row := q.db.QueryRow(ctx, getGroupMember, arg.GroupID, arg.UserID)
	var i GetGroupMemberRow
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Role,
		&i.Status,
		&i.BaselinePicks,
		&i.JoinedAt,
	)
	return i, err
}

const insertMembership = `-- name: InsertMembership :one
INSERT INTO memberships (group_id, user_id, role, status, baseline_picks, rotation_position)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, group_id, user_id, role, status, baseline_picks, rotation_position, joined_at, left_at
`

type InsertMembershipParams struct {
	GroupID          uuid.UUID        `json:"group_id"`
	UserID           uuid.UUID        `json:"user_id"`
	Role             MembershipRole   `json:"role"`
	Status           MembershipStatus `json:"status"`
	BaselinePicks    int32            `json:"baseline_picks"`
	RotationPosition int32            `json:"rotation_position"`
}

func (q *Queries) InsertMembership(ctx context.Context, arg InsertMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, insertMembership,
		arg.GroupID,
		arg.UserID,
		arg.Role,
		arg.Status,
		arg.BaselinePicks,
		arg.RotationPosition,
	)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.BaselinePicks,
		&i.RotationPosition,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const maxRotationPosition = `-- name: MaxRotationPosition :one
SELECT COALESCE(MAX(rotation_position), 0)::int AS max_position
FROM memberships
WHERE group_id = $1
`

func (q *Queries) MaxRotationPosition(ctx context.Context, groupID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, maxRotationPosition, groupID)
	var max_position int32
	err := row.Scan(&max_position)
	return max_position, err
}

const memberCreditedCount = `-- name: MemberCreditedCount :one
SELECT COALESCE(COUNT(*) FILTER (WHERE is_credited), 0)::int AS credited_count
FROM picks
WHERE group_id = $1 AND picker_id = $2
`

type MemberCreditedCountParams struct {
	GroupID uuid.UUID   `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) MemberCreditedCount(ctx context.Context, arg MemberCreditedCountParams) (int32, error) {
	row := q.db.QueryRow(ctx, memberCreditedCount, arg.GroupID, arg.UserID)
	var credited_count int32
	err := row.Scan(&credited_count)
	return credited_count, err
}

const promoteMembership = `-- name: PromoteMembership :one
UPDATE memberships
SET role = 'core', status = 'active', left_at = NULL,
    baseline_picks = $1, rotation_position = $2
WHERE group_id = $3 AND user_id = $4
RETURNING id, group_id, user_id, role, status, baseline_picks, rotation_position, joined_at, left_at
`

type PromoteMembershipParams struct {
	BaselinePicks    int32     `json:"baseline_picks"`
	RotationPosition int32     `json:"rotation_position"`
	GroupID          uuid.UUID `json:"group_id"`
	UserID           uuid.UUID `json:"user_id"`
}

func (q *Queries) PromoteMembership(ctx context.Context, arg PromoteMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, promoteMembership,
		arg.BaselinePicks,
		arg.RotationPosition,
		arg.GroupID,
		arg.UserID,
	)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.BaselinePicks,
		&i.RotationPosition,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}

const reactivateMembership = `-- name: ReactivateMembership :one
UPDATE memberships
SET status = 'active', left_at = NULL, baseline_picks = $1
WHERE group_id = $2 AND user_id = $3
RETURNING id, group_id, user_id, role, status, baseline_picks, rotation_position, joined_at, left_at
`

type ReactivateMembershipParams struct {
	BaselinePicks int32     `json:"baseline_picks"`
	GroupID       uuid.UUID `json:"group_id"`
	UserID        uuid.UUID `json:"user_id"`
}

func (q *Queries) ReactivateMembership(ctx context.Context, arg ReactivateMembershipParams) (Membership, error) {
	row := q.db.QueryRow(ctx, reactivateMembership, arg.BaselinePicks, arg.GroupID, arg.UserID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.BaselinePicks,
		&i.RotationPosition,
		&i.JoinedAt,
		&i.LeftAt,
	)
	return i, err
}
