// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: movies.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getMovie = `-- name: GetMovie :one
SELECT id, tmdb_id, title, release_year, cached_at, poster_path
FROM movies
WHERE id = $1
`

func (q *Queries) GetMovie(ctx context.Context, id uuid.UUID) (Movie, error) {
	row := q.db.QueryRow(ctx, getMovie, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.Title,
		&i.ReleaseYear,
		&i.CachedAt,
		&i.PosterPath,
	)
	return i, err
}

const setNightMovie = `-- name: SetNightMovie :one
UPDATE picks
SET movie_id = $1
WHERE id = $2 AND group_id = $3
RETURNING id, group_id, picker_id, is_credited, scheduled_for, created_at, movie_id
`

type SetNightMovieParams struct {
	MovieID pgtype.UUID `json:"movie_id"`
	NightID uuid.UUID   `json:"night_id"`
	GroupID uuid.UUID   `json:"group_id"`
}

func (q *Queries) SetNightMovie(ctx context.Context, arg SetNightMovieParams) (Pick, error) {
	row := q.db.QueryRow(ctx, setNightMovie, arg.MovieID, arg.NightID, arg.GroupID)
	var i Pick
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.PickerID,
		&i.IsCredited,
		&i.ScheduledFor,
		&i.CreatedAt,
		&i.MovieID,
	)
	return i, err
}

const upsertMovie = `-- name: UpsertMovie :one
INSERT INTO movies (tmdb_id, title, release_year, poster_path)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tmdb_id) DO UPDATE
    SET title = excluded.title, release_year = excluded.release_year,
        poster_path = excluded.poster_path, cached_at = now()
RETURNING id, tmdb_id, title, release_year, cached_at, poster_path
`

type UpsertMovieParams struct {
	TmdbID      int32       `json:"tmdb_id"`
	Title       string      `json:"title"`
	ReleaseYear pgtype.Int4 `json:"release_year"`
	PosterPath  pgtype.Text `json:"poster_path"`
}

func (q *Queries) UpsertMovie(ctx context.Context, arg UpsertMovieParams) (Movie, error) {
	row := q.db.QueryRow(ctx, upsertMovie,
		arg.TmdbID,
		arg.Title,
		arg.ReleaseYear,
		arg.PosterPath,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.Title,
		&i.ReleaseYear,
		&i.CachedAt,
		&i.PosterPath,
	)
	return i, err
}
