// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nights.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addAttendee = `-- name: AddAttendee :exec
INSERT INTO attendances (pick_id, user_id)
VALUES ($1, $2)
ON CONFLICT (pick_id, user_id) DO NOTHING
`

type AddAttendeeParams struct {
	PickID uuid.UUID `json:"pick_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) AddAttendee(ctx context.Context, arg AddAttendeeParams) error {
	_, err := q.db.Exec(ctx, addAttendee, arg.PickID, arg.UserID)
	return err
}

const createNight = `-- name: CreateNight :one
INSERT INTO picks (group_id, scheduled_for)
VALUES ($1, $2)
RETURNING id, group_id, picker_id, is_credited, scheduled_for, created_at
`

type CreateNightParams struct {
	GroupID      uuid.UUID   `json:"group_id"`
	ScheduledFor pgtype.Date `json:"scheduled_for"`
}

func (q *Queries) CreateNight(ctx context.Context, arg CreateNightParams) (Pick, error) {
	row := q.db.QueryRow(ctx, createNight, arg.GroupID, arg.ScheduledFor)
	var i Pick
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.PickerID,
		&i.IsCredited,
		&i.ScheduledFor,
		&i.CreatedAt,
	)
	return i, err
}

const getCurrentNight = `-- name: GetCurrentNight :one
SELECT id, group_id, picker_id, is_credited, scheduled_for, created_at
FROM picks
WHERE group_id = $1 AND picker_id IS NULL
ORDER BY scheduled_for DESC, created_at DESC
LIMIT 1
`

func (q *Queries) GetCurrentNight(ctx context.Context, groupID uuid.UUID) (Pick, error) {
	row := q.db.QueryRow(ctx, getCurrentNight, groupID)
	var i Pick
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.PickerID,
		&i.IsCredited,
		&i.ScheduledFor,
		&i.CreatedAt,
	)
	return i, err
}

const getNight = `-- name: GetNight :one
SELECT id, group_id, picker_id, is_credited, scheduled_for, created_at
FROM picks
WHERE id = $1 AND group_id = $2 AND picker_id IS NULL
`

type GetNightParams struct {
	NightID uuid.UUID `json:"night_id"`
	GroupID uuid.UUID `json:"group_id"`
}

func (q *Queries) GetNight(ctx context.Context, arg GetNightParams) (Pick, error) {
	row := q.db.QueryRow(ctx, getNight, arg.NightID, arg.GroupID)
	var i Pick
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.PickerID,
		&i.IsCredited,
		&i.ScheduledFor,
		&i.CreatedAt,
	)
	return i, err
}

const listNightAttendees = `-- name: ListNightAttendees :many
SELECT u.id, u.name, m.role
FROM attendances a
JOIN users u ON u.id = a.user_id
JOIN memberships m ON m.user_id = a.user_id AND m.group_id = $1
WHERE a.pick_id = $2
ORDER BY
  CASE WHEN m.role = 'core' THEN 0 ELSE 1 END,
  u.name
`

type ListNightAttendeesParams struct {
	GroupID uuid.UUID `json:"group_id"`
	NightID uuid.UUID `json:"night_id"`
}

type ListNightAttendeesRow struct {
	ID   uuid.UUID      `json:"id"`
	Name string         `json:"name"`
	Role MembershipRole `json:"role"`
}

func (q *Queries) ListNightAttendees(ctx context.Context, arg ListNightAttendeesParams) ([]ListNightAttendeesRow, error) {
	rows, err := q.db.Query(ctx, listNightAttendees, arg.GroupID, arg.NightID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNightAttendeesRow
	for rows.Next() {
		var i ListNightAttendeesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAttendee = `-- name: RemoveAttendee :exec
DELETE FROM attendances
WHERE pick_id = $1 AND user_id = $2
`

type RemoveAttendeeParams struct {
	PickID uuid.UUID `json:"pick_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveAttendee(ctx context.Context, arg RemoveAttendeeParams) error {
	_, err := q.db.Exec(ctx, removeAttendee, arg.PickID, arg.UserID)
	return err
}
