// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: picks.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertPick = `-- name: InsertPick :one
INSERT INTO picks (group_id, picker_id, is_credited, scheduled_for)
VALUES ($1, $2, $3, $4)
RETURNING id, group_id, picker_id, is_credited, scheduled_for, created_at
`

type InsertPickParams struct {
	GroupID      uuid.UUID   `json:"group_id"`
	PickerID     pgtype.UUID `json:"picker_id"`
	IsCredited   bool        `json:"is_credited"`
	ScheduledFor pgtype.Date `json:"scheduled_for"`
}

func (q *Queries) InsertPick(ctx context.Context, arg InsertPickParams) (Pick, error) {
	row := q.db.QueryRow(ctx, insertPick,
		arg.GroupID,
		arg.PickerID,
		arg.IsCredited,
		arg.ScheduledFor,
	)
	var i Pick
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.PickerID,
		&i.IsCredited,
		&i.ScheduledFor,
		&i.CreatedAt,
	)
	return i, err
}
