// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roster.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT u.id, u.name, m.role, m.status, m.joined_at
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.group_id = $1
ORDER BY
  CASE
    WHEN m.status = 'active' AND m.role = 'core'  THEN 0
    WHEN m.status = 'active' AND m.role = 'guest' THEN 1
    ELSE 2
  END,
  m.rotation_position,
  u.name
`

type ListGroupMembersRow struct {
	ID       uuid.UUID          `json:"id"`
	Name     string             `json:"name"`
	Role     MembershipRole     `json:"role"`
	Status   MembershipStatus   `json:"status"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) ListGroupMembers(ctx context.Context, groupID uuid.UUID) ([]ListGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupMembersRow
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Status,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
