// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roster.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT u.id, u.name, m.role
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.group_id = $1
  AND m.status = 'active'
ORDER BY m.rotation_position, u.name
`

type ListGroupMembersRow struct {
	ID   uuid.UUID      `json:"id"`
	Name string         `json:"name"`
	Role MembershipRole `json:"role"`
}

func (q *Queries) ListGroupMembers(ctx context.Context, groupID uuid.UUID) ([]ListGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupMembersRow
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
