// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: turn.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const rankGroupTurn = `-- name: RankGroupTurn :many
SELECT u.id, u.name, m.role,
       (m.baseline_picks + COALESCE(p.credited_count, 0))::int AS served_count,
       p.last_picked_on
FROM memberships m
JOIN users u ON u.id = m.user_id
LEFT JOIN (
  SELECT picker_id,
         COUNT(*) FILTER (WHERE is_credited)           AS credited_count,
         (MAX(scheduled_for) FILTER (WHERE is_credited))::date AS last_picked_on
  FROM picks
  WHERE picks.group_id = $1
  GROUP BY picker_id
) p ON p.picker_id = m.user_id
WHERE m.group_id = $1
  AND m.status = 'active'
  AND m.role = 'core'
  AND ($2::uuid[] IS NULL OR u.id = ANY($2::uuid[]))
ORDER BY served_count ASC, last_picked_on ASC NULLS FIRST, m.rotation_position ASC
`

type RankGroupTurnParams struct {
	GroupID uuid.UUID   `json:"group_id"`
	Present []uuid.UUID `json:"present"`
}

type RankGroupTurnRow struct {
	ID           uuid.UUID      `json:"id"`
	Name         string         `json:"name"`
	Role         MembershipRole `json:"role"`
	ServedCount  int32          `json:"served_count"`
	LastPickedOn pgtype.Date    `json:"last_picked_on"`
}

func (q *Queries) RankGroupTurn(ctx context.Context, arg RankGroupTurnParams) ([]RankGroupTurnRow, error) {
	rows, err := q.db.Query(ctx, rankGroupTurn, arg.GroupID, arg.Present)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RankGroupTurnRow
	for rows.Next() {
		var i RankGroupTurnRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.ServedCount,
			&i.LastPickedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
